language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_ATLAS="true"
      NUMPY_VERSION="1.7.1" SCIPY_VERSION="0.13.2" CVXOPT_VERSION="1.1.6"
      COVERAGE="true" ATLAS="/usr/lib/atlas-base/"
install:
  - pip install conda
  - conda init
  - conda install atlas numpy=1.7.1 scipy=0.13.2 cvxopt nose
script: bash continuous_integration/test_script.sh
after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls; fi
cache: apt