language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" INSTALL_ATLAS="true"
      NUMPY_VERSION="1.7.1" SCIPY_VERSION="0.13.2" CVXOPT_VERSION="1.1.6"
      COVERAGE="true"
install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls; fi
cache: apt