language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-numpy python-scipy python-cvxopt
# install dependencies
install:
    - pip install coverage
    - sudo python travis_setup.py install
# command to run tests
script:
    - nosetests --with-cover --cover-package=cvxpy
